<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PositionsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('positions')->insert([
            [
                'title' => 'Frontend Developer Intern',
                'department' => 'Technology',
                'description' => 'Membantu tim pengembangan dalam membangun antarmuka web menggunakan React dan Tailwind. Berkolaborasi dengan UI/UX Designer untuk implementasi desain.',
                'requirements' => 'Menguasai dasar HTML, CSS, JavaScript, dan framework frontend seperti React atau Vue. Memiliki minat di bidang UI/UX.',
                'quota' => 3,
                'deadline' => '2025-12-15',
                'status' => 'open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Backend Developer Intern',
                'department' => 'Technology',
                'description' => 'Bertanggung jawab dalam mengembangkan dan memelihara API backend menggunakan Laravel. Membantu dalam integrasi sistem dengan database MySQL.',
                'requirements' => 'Menguasai PHP dan Laravel. Memahami konsep REST API dan database relational.',
                'quota' => 2,
                'deadline' => '2025-12-10',
                'status' => 'open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'UI/UX Designer Intern',
                'department' => 'Design',
                'description' => 'Berpartisipasi dalam riset pengguna, membuat wireframe, dan prototipe desain untuk aplikasi web dan mobile.',
                'requirements' => 'Menguasai Figma atau Adobe XD. Memahami dasar-dasar user experience design dan visual hierarchy.',
                'quota' => 2,
                'deadline' => '2025-12-20',
                'status' => 'open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Digital Marketing Intern',
                'department' => 'Marketing',
                'description' => 'Membantu pelaksanaan kampanye digital melalui media sosial, SEO, dan email marketing. Melakukan analisis performa kampanye.',
                'requirements' => 'Aktif di media sosial, memahami dasar copywriting dan Google Analytics. Kreatif dan komunikatif.',
                'quota' => 3,
                'deadline' => '2025-12-25',
                'status' => 'open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Content Writer Intern',
                'department' => 'Marketing',
                'description' => 'Membuat artikel dan konten untuk website dan media sosial perusahaan. Fokus pada konten edukatif dan branding.',
                'requirements' => 'Pandai menulis, memiliki kemampuan riset yang baik, dan memahami SEO dasar.',
                'quota' => 2,
                'deadline' => '2025-12-18',
                'status' => 'open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Graphic Designer Intern',
                'department' => 'Design',
                'description' => 'Membantu tim marketing dan produk dalam pembuatan materi grafis seperti poster, banner, dan konten media sosial.',
                'requirements' => 'Menguasai Adobe Photoshop/Illustrator/CorelDRAW. Kreatif dan memiliki portofolio desain.',
                'quota' => 2,
                'deadline' => '2025-12-12',
                'status' => 'open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Data Analyst Intern',
                'department' => 'Business Intelligence',
                'description' => 'Mengumpulkan, membersihkan, dan menganalisis data operasional perusahaan untuk membantu pengambilan keputusan.',
                'requirements' => 'Menguasai Excel/Google Sheets dan dasar SQL. Memahami analisis data dan visualisasi (Power BI/Tableau nilai plus).',
                'quota' => 2,
                'deadline' => '2025-12-30',
                'status' => 'open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'HR Intern',
                'department' => 'Human Resources',
                'description' => 'Mendukung kegiatan rekrutmen, administrasi karyawan, dan pengelolaan data kehadiran.',
                'requirements' => 'Mahasiswa Psikologi, Manajemen, atau sejenisnya. Teliti dan komunikatif.',
                'quota' => 2,
                'deadline' => '2025-12-05',
                'status' => 'open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Finance Intern',
                'department' => 'Finance',
                'description' => 'Membantu proses pencatatan transaksi keuangan dan penyusunan laporan bulanan.',
                'requirements' => 'Mahasiswa Akuntansi/Manajemen Keuangan. Menguasai Excel dan dasar akuntansi.',
                'quota' => 1,
                'deadline' => '2025-12-22',
                'status' => 'open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Customer Service Intern',
                'department' => 'Operations',
                'description' => 'Berinteraksi dengan pelanggan, menangani pertanyaan, dan memastikan kepuasan pengguna.',
                'requirements' => 'Komunikatif, sabar, dan memiliki kemampuan interpersonal yang baik.',
                'quota' => 3,
                'deadline' => '2025-12-28',
                'status' => 'open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Project Management Intern',
                'department' => 'Operations',
                'description' => 'Mendukung manajer proyek dalam koordinasi tim, pembuatan laporan progres, dan dokumentasi proyek.',
                'requirements' => 'Memiliki kemampuan organisasi dan komunikasi yang baik. Mahir menggunakan Google Workspace.',
                'quota' => 1,
                'deadline' => '2025-12-17',
                'status' => 'open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Video Editor Intern',
                'department' => 'Creative',
                'description' => 'Membuat dan mengedit video promosi, dokumentasi kegiatan, serta konten media sosial.',
                'requirements' => 'Menguasai Adobe Premiere Pro/CapCut. Kreatif dan memahami storytelling visual.',
                'quota' => 2,
                'deadline' => '2025-12-27',
                'status' => 'open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
