<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class UsersSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            // 🧑‍💼 Admins
            [
                'name' => 'Andi Pratama',
                'email' => 'admin@example.com',
                'password' => Hash::make('password'),
                'role' => 'admin',
                'school_name' => null,
                'major' => null,
                'education_level' => null,
                'phone' => '081234567890',
                'address' => 'Jakarta Selatan, DKI Jakarta',
                'profile_photo' => 'profiles/andi.jpg',
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rina Kartika',
                'email' => 'admin1@example.com',
                'password' => Hash::make('password'),
                'role' => 'admin',
                'school_name' => null,
                'major' => null,
                'education_level' => null,
                'phone' => '081298765432',
                'address' => 'Bandung, Jawa Barat',
                'profile_photo' => 'profiles/rina.jpg',
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 🎓 Students (14)
            [
                'name' => 'Budi Santoso',
                'email' => 'student1@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'school_name' => 'SMK Negeri 1 Jakarta',
                'major' => 'Teknik Komputer dan Jaringan',
                'education_level' => 'SMK',
                'phone' => '081345678901',
                'address' => 'Jakarta Timur, DKI Jakarta',
                'profile_photo' => 'profiles/budi.jpg',
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Siti Aisyah',
                'email' => 'student2@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'school_name' => 'Universitas Indonesia',
                'major' => 'Psikologi',
                'education_level' => 'Universitas',
                'phone' => '081312345678',
                'address' => 'Depok, Jawa Barat',
                'profile_photo' => 'profiles/siti.jpg',
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rizky Hidayat',
                'email' => 'student3@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'school_name' => 'SMK Telkom Malang',
                'major' => 'Rekayasa Perangkat Lunak',
                'education_level' => 'SMK',
                'phone' => '081276543210',
                'address' => 'Malang, Jawa Timur',
                'profile_photo' => 'profiles/rizky.jpg',
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dewi Lestari',
                'email' => 'student4@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'school_name' => 'Universitas Gadjah Mada',
                'major' => 'Akuntansi',
                'education_level' => 'Universitas',
                'phone' => '081223456789',
                'address' => 'Yogyakarta',
                'profile_photo' => 'profiles/dewi.jpg',
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Agus Saputra',
                'email' => 'student5@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'school_name' => 'SMK Negeri 2 Surabaya',
                'major' => 'Teknik Elektronika Industri',
                'education_level' => 'SMK',
                'phone' => '081365432187',
                'address' => 'Surabaya, Jawa Timur',
                'profile_photo' => 'profiles/agus.jpg',
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maya Sari',
                'email' => 'student6@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'school_name' => 'Universitas Airlangga',
                'major' => 'Kedokteran',
                'education_level' => 'Universitas',
                'phone' => '081345671234',
                'address' => 'Surabaya, Jawa Timur',
                'profile_photo' => 'profiles/maya.jpg',
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hendra Wijaya',
                'email' => 'student7@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'school_name' => 'SMK Negeri 5 Bandung',
                'major' => 'Teknik Otomotif',
                'education_level' => 'SMK',
                'phone' => '081278945612',
                'address' => 'Bandung, Jawa Barat',
                'profile_photo' => 'profiles/hendra.jpg',
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Clara Wijayanti',
                'email' => 'student8@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'school_name' => 'Universitas Brawijaya',
                'major' => 'Teknik Informatika',
                'education_level' => 'Universitas',
                'phone' => '081278934561',
                'address' => 'Malang, Jawa Timur',
                'profile_photo' => 'profiles/clara.jpg',
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rahmat Fauzi',
                'email' => 'student9@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'school_name' => 'SMK Negeri 3 Medan',
                'major' => 'Teknik Kendaraan Ringan',
                'education_level' => 'SMK',
                'phone' => '081287654321',
                'address' => 'Medan, Sumatera Utara',
                'profile_photo' => 'profiles/rahmat.jpg',
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nina Aprilia',
                'email' => 'student10@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'school_name' => 'Universitas Padjadjaran',
                'major' => 'Ilmu Komunikasi',
                'education_level' => 'Universitas',
                'phone' => '081398765412',
                'address' => 'Sumedang, Jawa Barat',
                'profile_photo' => 'profiles/nina.jpg',
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Doni Prakoso',
                'email' => 'student11@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'school_name' => 'SMK Negeri 4 Yogyakarta',
                'major' => 'Multimedia',
                'education_level' => 'SMK',
                'phone' => '081234567812',
                'address' => 'Yogyakarta',
                'profile_photo' => 'profiles/doni.jpg',
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lina Marlina',
                'email' => 'student12@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'school_name' => 'Universitas Sebelas Maret',
                'major' => 'Sastra Inggris',
                'education_level' => 'Universitas',
                'phone' => '081399887766',
                'address' => 'Solo, Jawa Tengah',
                'profile_photo' => 'profiles/lina.jpg',
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Taufik Rahman',
                'email' => 'student13@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'school_name' => 'SMK Negeri 6 Semarang',
                'major' => 'Desain Komunikasi Visual',
                'education_level' => 'SMK',
                'phone' => '081245671234',
                'address' => 'Semarang, Jawa Tengah',
                'profile_photo' => 'profiles/taufik.jpg',
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Putri Anggraini',
                'email' => 'student14@example.com',
                'password' => Hash::make('password'),
                'role' => 'student',
                'school_name' => 'Universitas Diponegoro',
                'major' => 'Hukum',
                'education_level' => 'Universitas',
                'phone' => '081378945612',
                'address' => 'Semarang, Jawa Tengah',
                'profile_photo' => 'profiles/putri.jpg',
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
